version: '3.1'
services:

  php-apache:   
    ## Grazie a build posso collegare al docker compose un dockerfiles.
    ## con il context gli dico dove prendere il Dockerfile. Mettendo il . (punto) dico a docker di prenderlo nella
    ## stessa cartella dove risiede docker-compose.yml
    ## in questo caso ho aggiunto un Dockerfile per aggiunger il modulo pdo_mysql a php 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ../dockerPhp:/var/www/html/ 
    ports:
      - 8000:80
    
  db:
    container_name: mysqlDatabase
    platform: linux/amd64 
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../dockerMysql:/var/lib/mysql
  
  phpMyAdmin:
    container_name: phpMyAdmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dario
      MYSQL_PASSWORD: root

  

   